version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql:3306/testdb
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mysql_data: